steps:
- name: node:14.10.1
  entrypoint: npm
  args: ["install"]
- name: node:14.10.1
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'DISCORD_BOT_ID=${_DISCORD_BOT_ID}'
    - 'DISCORD_CLIENT_ID=${_DISCORD_CLIENT_ID}'
    - 'NODE_ENV=production'
- name: node:14.10.1
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "-v", "main-1", "--promote"]
timeout: "1600s"